### ISSUE TITLE
"Could not load your book" -error

### ISSUE THREAD

**Issue by joreg** [GitbookIO/feedback#344] opened 2017-02-04 14:19 UTC
## Category
bug

## What is the current behavior?
recently my book shows: "Could not load your book. Check your book.json for errors" in the bottom left corner. 

the content of book.json hasn't changed before the error occurred and is still:
{
"structure": {
"readme": "README.adoc"
}
}

most things seem to work though. the only thing i notice is that in the editor some pages don't show their preview on the right side but just a blank page...not sure if related though?!

EDIT: even setting its content to { } doesn't get rid of the error.

## Additional information
- win10
- chrome55

**Comment by Soreine** [comment] 2017-03-09 12:09
This looks like a duplicate of https://github.com/GitbookIO/feedback/issues/411
This should be fixed in the [Editor v7.0.10](https://www.gitbook.com/editor/releases/stable#7.0.10). The Web Editor will be updated during the day.

**Closed by Soreine** 2017-03-09 12:09 UTC
