### ISSUE TITLE
Feature Request - [ctrl+F] to search the content in the book ...

### ISSUE THREAD

**Issue by V0idk** [GitbookIO/feedback#383] opened 2017-02-26 03:04 UTC
# What is the desired behavior?
it wil be more convennient。

**Comment by manngo** [comment] 2017-02-28 10:40
According to the keyboard shortcuts it should be working already. (I use a Mac, so it’s supposed to be ⌘F). It doesn’t work.

**Comment by Soreine** [comment] 2017-03-08 10:56
Duplicate of #123

**Closed by Soreine** 2017-03-08 10:56 UTC
