### ISSUE TITLE
version6.1.0 : copy then paste, format not good

### ISSUE THREAD

**Issue by singi2016cn** [GitbookIO/feedback#100] opened 2016-07-20 06:47 UTC
##copy some code,then paste,format bad!
###copy format:
```
{
    "name":"singi",
    "notlike":"version 6.1.0"
}
```
###paste format
```
{ "name":"singi", "notlike":"version 6.1.0" }
```
##may I paste the same as copy?just do as old version,you do! 
###thank you for your working.

**Comment by SamyPesse** [comment] 2016-07-20 07:42
This is a duplicate of #83.

I'm closing this one, we are working on it.

**Closed by SamyPesse** 2016-07-20 07:42 UTC
Labels: duplicate
