### ISSUE TITLE
Editor 6.2.1: Paste issues

### ISSUE THREAD

**Issue by lindexi** [GitbookIO/feedback#155] opened 2016-08-26 00:41 UTC
I copy the text but cant paste it,and I can paste in notepad.
- Operating System?
  Windows 10 x64
- (Web) Browser version?
- (Desktop) Editor version? 6.2.1

The 4.2 is good than lastest but you call me to update but the 6.2.1 cant paster and font is small and I cant use it.

**Comment by CharlesWiltgen** [comment] 2016-08-28 19:06
I can confirm cut/copy/paste issues on 6.2.1/Mac. (It would be really cool to be able to drag selected text as well!)

**Comment by julian-t** [comment] 2016-09-12 15:38
6.2.1 on OS X 10.10.5 definitely has copy/paste problems. I've noticed the following:
* pasting into code block results in smaller text
* after copying and pasting a block of text, edits to the original block often result in the pasted copy disappearing

**Comment by shadowbq** [comment] 2016-09-19 02:38
Ubuntu on Gitbook Editor 6.2.1 confirmed issues with copy/paste

**Comment by shadowbq** [comment] 2016-09-22 16:18
More explicitly there are issues with the key bindings of cut copy paste, as well newline characters not copy as well.

**Comment by yangxuan8282** [comment] 2016-09-23 07:14
same issues on Win10 64bit, the `paste` on menu not work either

**Comment by Soreine** [comment] 2016-09-30 09:55
This was an important issue, that should be fixed in version `6.3.0`. It should be fixed in the upcoming pre-release version `6.3.0-alpha.1`.

**Comment by Soreine** [comment] 2016-09-30 10:05
I'm keeping this issue open as a reference of pasting problems. I'll close it when `6.3.0` will be released with the issue fixed.

**Comment by davy39** [comment] 2016-10-16 18:06
Hi,
I'm using Gitbook on a linux mint system.
I did have some Ctrl+V issues with 6.2.1, seems to be better with 6.3.0
However still no way to drag and drop some text.
Could you try to implement this please ?

**Comment by Soreine** [comment] 2016-12-21 08:48
@davy39 I have moved your feature request to an independent issue https://github.com/GitbookIO/feedback/issues/279

**Closed by Soreine** 2016-12-21 08:48 UTC
Labels: bug, editor

**Comment by lindexi** [comment] 2016-12-21 08:50
@Soreine Thx.My app can be updated for the bad Connect.

**Comment by lijicheng123** [comment] 2019-01-08 09:21
in Editor 7.0.12,copy and paste doesn't work with mac os 10.13.2,
and when page arrived bottom ,i type in word with space key ,sometimes will back to top
