### ISSUE TITLE
gitbook editor 6.3.0  dis-fluency when using Chinese input method，window 10 and window 7 both involved.

### ISSUE THREAD

**Issue by HuanGong** [GitbookIO/feedback#244] opened 2016-12-01 13:36 UTC
## gitbook editor 6.3.0  

gitbook editor 6.3.0  dis-fluency when using Chinese input method，window 10 and window 7 both involved.

Thanks for your great Job

**Comment by SamyPesse** [comment] 2016-12-05 21:53
Thanks, It seems to be a duplicate of #232

Closing this one.

**Closed by SamyPesse** 2016-12-05 21:53 UTC
Labels: bug, editor

**Comment by HuanGong** [comment] 2016-12-11 03:38
good job, thanks. it seems ok in version 6.3.7
