### ISSUE TITLE
Long words in the book name/description are breaking the Dashboard page

### ISSUE THREAD

**Issue by imbacile** [GitbookIO/feedback#243] opened 2016-12-01 12:19 UTC
## Category

Bug

## What is the current behavior?

The /dashboard page with new design breaks with a long words. 

![screen shot 2016-12-01 at 15 15 40](https://cloud.githubusercontent.com/assets/24294251/20793667/2c589bac-b7d9-11e6-8108-10ba5eb9412c.png)

## What is the desired behavior?

Better and more responsive design?

## Additional information

https://www.gitbook.com/@vladgolovach/dashboard

**Comment by nagim** [comment] 2016-12-01 20:03
It's already reported in #238.

**Comment by SamyPesse** [comment] 2016-12-05 21:54
Closing this one as duplicate of #238

**Closed by SamyPesse** 2016-12-05 21:54 UTC
Labels: duplicate
