### ISSUE TITLE
CSS and layout changes not applied at the same time

### ISSUE THREAD

**Issue by Mackiovello** [GitbookIO/feedback#313] opened 2017-01-17 17:45 UTC
## Category

Building and publishing of GitBooks

## What is the current behavior?

1. After creating changes in the layout, for example, in `_layout/website/header.html` and adding styling in `style.css` push the changes to GitHub and let GitBook build the new version.

2. Open your GitBook and inspect the changes in the layout.

3. In some cases, the layout changes will be applied before the styling is applied. This becomes very clear when adding items and styling in the same commit. 

After some time the styling is applied and the page looks as intended.

## What is the desired behavior?

Styling and layout change should be displayed at the same time.

## Additional information

* I'm making the changes in a text editor (Atom). 

* CLI version: 2.3.0

* GitBook version: 3.2.2

* The GitBook is found at [docs.starcounter.com](https://docs.starcounter.io/v/2.1.177/)

If there's a need for it, I would be happy to recreate it and document the issue more clearly.

**Comment by Mackiovello** [comment] 2017-01-18 10:34
This happened again today. I added some new elements with some styling and pushed it to GitHub. When I checked the GitBook a couple of minutes later it looked like this:
![wrong](https://cloud.githubusercontent.com/assets/19392292/22060632/db33be96-dd71-11e6-8ecf-5492e3307373.PNG)
If I instead run `gitbook serve` the css is applied and it looks like this:
![right](https://cloud.githubusercontent.com/assets/19392292/22060649/ebfa9d30-dd71-11e6-9c04-fe232ebdcbb3.PNG)

**Comment by lazaridis-com** [comment] 2017-03-28 10:05
@Mackiovello , just to be sure: have you tried reloading the page whilst clearing the browser cache?

https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Bypassing_cache

**Comment by lazaridis-com** [comment] 2017-03-28 10:08
@AaronO , if this is a browser-cache issue, the the action would be:

* minimal: In the Gitbook user-interface, remind the user that he has to clear the browser cache
* ideal: provide the (server-side) means, thus cache-update are enforced (after css etc. is updated)

**Comment by Mackiovello** [comment] 2017-03-28 10:09
> @Mackiovello , just to be sure: have you tried reloading the page whilst clearing the browser cache? 

Yes, that has been tried. I'm pretty certain that it is a server-side issue.

**Comment by AaronO** [comment] 2017-03-28 10:18
@Mackiovello @lazaridis-com We invalidate our CDN cache when a new successful build has completed. This ensures that all content / HTML on our content edges is fresh at most a few seconds after a build has finished.

However our CDN does set a `Cache-Control` header to leverage browser caching for all non-html assets (`.css`, `.js`, ...). This is likely what you're seeing

@Mackiovello I noticed that you have Cloudflare in front of our CDN, which has a much more aggressive caching policy on non-HTML assets. Compare the following `cache-control` headers for `.css` files:

### Our CDN

```
cache-control:max-age=600, public
```

### Cloudflare's Cache-Control

```
cache-control:public, max-age=14400
```

### Conclusion

Our CDN leverages browser caching for up-to **10 minutes** before requiring the browser to revalidate with the server/CDN, Cloudflare tells the browser to cache for up-to **4 hours** before revalidating.

**Comment by lazaridis-com** [comment] 2017-03-28 10:31
@AaronO , what **Actions** do you suggest?

* What can this user do (to solve/workaround the issue)?
* What can you do thus other users do not hit on this issue?

**Comment by AaronO** [comment] 2017-03-28 10:37
@lazaridis-com I'm first explaining the issue (because caching is trade-off), you can't effectively solve a problem if you haven't identified the cause.

There are a few possible actions:
- Configure Cloudlfare to set a much lower `cache-control` timeout
- Disable Cloudflare's caching/proxying for the domain (so that our CDN sends its lower `cache-control` timeout)
- Accept Cloudflare's aggressive timeout and that some CSS/JS/IMAGE assets may be cached by the reader's browser longer than expected.

Users that use our CDN and don't layer Cloudflare on top should not encounter this issue, or to a very limited extent since our CDN tells the browser to cache only for 10mn which is 24x shorter than Cloudflare's 4h.

**Comment by Mackiovello** [comment] 2017-03-28 10:39
> There are a few possible actions:

Thank you! That's very useful.

@warpech, would it be possible for you to disable caching for the docs domain at CloudFlare?

**Comment by lazaridis-com** [comment] 2017-03-28 10:54
> or to a very limited extent since our CDN tells the browser to cache only for 10mn

@AaronO , this is much time, so other users can hit on this issue, even without using Cloudflare or similar services. What actions can you take to avoid this?

minimal action: place a note in your documentation/ui ("You may need to clear your browsers cache after changing your template/css. CTRL-F5 for firefox, ... ")

**Comment by warpech** [comment] 2017-03-28 10:54
This indeed looks strange that Cloudflare rewrites 10 minutes to 4 hours. I think I can change that to be 10 minutes too. 

Disabling CloudFlare seems a wrong approach. CloudFlare and GitBook should work together and do their intended job respectively :)

Cloudflare users: You can also log in to your CloudFlare panel to purge the cache manually.

To avoid such problem, @AaronO may I suggest that Gitbook implements ETag headers? Cloudflare  respects them. See: https://support.cloudflare.com/hc/en-us/articles/218505467-Does-Cloudflare-support-ETag-headers-

**Comment by warpech** [comment] 2017-03-28 10:57
FYI the "4 hours" setting can be changed easily in Cloudflare panel. I have done that for our setup.

<img width="976" alt="screen shot 2017-03-28 at 12 55 58" src="https://cloud.githubusercontent.com/assets/566463/24401773/00161a90-13b6-11e7-96da-3f779e08002e.png">

**Comment by AaronO** [comment] 2017-03-28 11:02
@warpech Cloudflare is doing it's job. It is strange that it's rewriting our `cache-control` header to 4 hours. I agree that disabling cloudflare shouldn't be the solution.

The issue is not server caching nor ETag invalidation, we implement ETags and correctly support them.

This is all about the browser and the `cache-control` header, basically this header tells the browser:
> This resource should be valid for at least N seconds, don't even try to revalidate it, you can use your load your local copy anytime you see this URL (so no requests are sent to the server whilst that local copy is valid)

If you set Cloudflare to "Respect Existing Headers" it will respect the `cache-control` header our CDN sends

**Comment by AaronO** [comment] 2017-04-04 10:19
@warpech @Mackiovello Is this good on your end or do you have further questions ?

**Comment by warpech** [comment] 2017-04-04 10:20
I think we are fine, thanks for your support!

**Comment by AaronO** [comment] 2017-04-04 10:21
@warpech Good to hear, thanks ! (closing this issue)

**Closed by AaronO** 2017-04-04 10:21 UTC

**Comment by lazaridis-com** [comment] 2017-04-04 19:23
@warpech , @Mackiovello - See? Sometimes, you have to push to make things happen. There are cases where you even have to cross a line or two. Once you accept this, and adopt it to yourself and Starbase, possibly you have a chance to produce a decent marketable product.
